### ISSUE TITLE
Children in JSX 

### ISSUE THREAD

**Issue by basarat** [krasimir/react-in-patterns#19]
Refering to : https://github.com/krasimir/react-in-patterns/tree/master/patterns/children-in-jsx 

I think: 

```tsx
        <i className='something-else'>
          { props.children }
        </i>
```

Should be : 

```tsx
        <i className='something-else' children={children}/>
```

Note that they are not equivalent. First one creates new children with a single item, the second one reuses the children. I've heard issues with the first pattern e.g. keys/ids confused React. Don't have an issue report as the second syntax fixed it :rose:

**Comment by krasimir** [comment]
That's interesting. I think I'm not seeing the difference and I'll be happy to explore that use case. The [test]() which I'm making is:
```js
```

**Comment by basarat** [comment]
# Whitespace issues
A quick example : https://jsfiddle.net/yrh6uLv5/ with code: 

```
function Hello1(props) {
  return <b children={ props.children } />;
}
function Hello2(props) {
  return <b> { props.children } </b>;
}

function App() {
  return (
    <div>
    <Hello1><div>test1-a</div><div>test1-b</div></Hello1>
    <Hello2><div>test2-a</div><div>test2-b</div></Hello2>
    </div>
  );
}

ReactDOM.render(
  <App />,
  document.getElementById('container')
);
```
Shows that it does open up the hazard of mistaken texts ... although unlikely in real code as people using JSX are generally aware of whitespace significance
![image](https://cloud.githubusercontent.com/assets/874898/21738585/cd87428e-d4db-11e6-8ff1-5202d2094d05.png)


I haven't been able to introduce the other. Will update if it ever comes up. Was hoping that this was already well understood :rose:

**Comment by krasimir** [comment]
Didn't know about those white space issues. But I think it is ok that we see them because there are whitespaces after the opening and closing tag. The following doesn't produce those `react-text` comments:
```
function Hello2(props) {
  return (
    <b>
      { props.children }
    </b>
  );
}
```
(by the way if I add the same spaces after the `<b>` and before `</b>` we again don't get `react-text`. So it looks like the new lines are cleaning up those.

Regarding the `key` warning like `Each child in an array or iterator should have a unique "key" prop.` I think this happen only if you generate children dynamically. In the example above the two `<div>`s are static tags and React shouldn't care about their keys because they don't change. While something like the following throws the warning:
```js
<Hello2>{ ['a', 'b'].map(entry => <p>{ entry }</p>) }</Hello2>
```
